# .circleci/config.yml
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.2.0"

    steps:
      - checkout
      - run:
          name: Unity Build
          command: |
            echo "Getting this message! Yaay!!!"


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test