# .circleci/config.yml
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.2.0"

    steps:
      - checkout
      - run:
          name: GIT Checkout
          command: |
          ./update-mapbox-unity-sdk-core.sh

      - run:
          name: Installing Unity
          command: |
          ./scripts/install.sh

      - run:
          name: Building the project
          command: |
          ./scripts/build.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test